name: chrome-thumbs
description: A powerful Chrome extension that displays visual thumbnails of all open tabs with advanced navigation and management capabilities
url: https://github.com/luopub/chrome-thumbs
created: 2025-12-19
last_modified: 2025-12-19
topics:
  - chrome-extension
  - tab-management
  - browser-extension
  - productivity
  - tab-thumbnails
  - tab-switcher
  - browser-tools
  - chrome
  - tabs
  - extension-development
  - visual-tabs
  - tab-previews
  - browsing-efficiency
  - tab-organization
  - chrome-store
  - manifest-v3